### PR TITLE
Cleanup files for Gerber builds

### PR DESCRIPTION
**Pull request by dolfelt**
I've updated the markdown and added the bare schematic to the builds. Let me know what you think.

### CODE REVIEW

**Comment by Kaldek** [comment]
> I've updated the markdown and added the bare schematic to the builds. Let me know what you think.

Just checking this request and it looks like modifications of text in the markdown files and removal of files from the Gerber folder only?

**Comment by dolfelt** [comment]
Yep!

**Comment by Kaldek** [comment]
Sorry mate, my actual question is "why".  😁

**Comment by dolfelt** [comment]
@Kaldek I removed all the Gerber files since they are now built with the Github Actions directly. This means there is less to commit and review in pull requests, and one less step to remember when updating the KiCad files.

As for the Markdown changes, I fixed a broken image link and maybe got carried away removing the hardcoded URL so that forks/pull requests can reference items local to their own repository before merging into the main one. My editor also removes trailing spaces, which is what some of those big block are. I didn't change any actual text in the Markdown.

Hope this was a decent explanation. 😅

**Comment by Kaldek** [comment]
Ah right, OK my noobiness shines through here; I didn't know it was possible for the files to be built automatically.    I am literally 3 weeks into Github, which is as embarrassing to me as it probably is to everyone else.

**Comment by dolfelt** [comment]
@Kaldek It doesn't show at all, and is impressive how much you've done in only 3 weeks! 👍

**Pull request merged**
