### PR TITLE
Update Using red wire for power.md

### PR DESCRIPTION
**Pull request by poldim**
Alternate option to power the ESP from the backup battery connector

### CODE REVIEW

**Comment by Kaldek** [comment]
My god, why didn't I think of this.  I literally have that on my GDO.

**Review by Kaldek — APPROVED** [review]

**Comment by poldim** [comment]
> My god, why didn't I think of this. I literally have that on my GDO.

Mine has been working great for years this way.  I don't have a backup battery, but so long as your utility stays on, you'll have DC here.

Feel free to add this pic from the manual:
image

**Comment by Kaldek** [comment]
Ah, mine is totally different to that.  It's an internally mounted battery.  I assume it uses the same connector type somewhere within the case but perhaps not.
image

**Comment by Kaldek** [comment]
@poldim maybe the better question is whether we can tap that circuit if there is no battery in use.  Charging circuits can get a little weird.

**Comment by poldim** [comment]
> @poldim maybe the better question is whether we can tap that circuit if there is no battery in use. Charging circuits can get a little weird.



See my comment above:
> Mine has been working great for years this way. I don't have a backup battery, but so long as your utility stays on, you'll have DC here.

**Comment by Kaldek** [comment]
> > @poldim maybe the better question is whether we can tap that circuit if there is no battery in use. Charging circuits can get a little weird.
> 
> See my comment above:
> 
> > Mine has been working great for years this way. I don't have a backup battery, but so long as your utility stays on, you'll have DC here.

Oh right, well that's really good news.

**Comment by bjhiltbrand** [comment]
That's a great option! One of my Chamberlain GDOs has battery backup, one does not. :( I'll see about adding the power regulation stuff back in in a new kicad variation.

**Pull request merged**
